/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as NewsRouteImport } from './routes/news'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramsIndexRouteImport } from './routes/programs.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProgramsSlugRouteImport } from './routes/programs.$slug'
import { Route as AdminSubmissionsRouteImport } from './routes/admin.submissions'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminProgramsRouteImport } from './routes/admin.programs'
import { Route as AdminNewsRouteImport } from './routes/admin.news'
import { Route as AdminHomeSettingsRouteImport } from './routes/admin.home-settings'
import { Route as AdminHeroSlidesRouteImport } from './routes/admin.hero-slides'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminDonationsRouteImport } from './routes/admin.donations'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminContactSettingsRouteImport } from './routes/admin.contact-settings'
import { Route as AdminAboutSettingsRouteImport } from './routes/admin.about-settings'

const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProgramsSlugRoute = ProgramsSlugRouteImport.update({
  id: '/programs/$slug',
  path: '/programs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProgramsRoute = AdminProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomeSettingsRoute = AdminHomeSettingsRouteImport.update({
  id: '/home-settings',
  path: '/home-settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHeroSlidesRoute = AdminHeroSlidesRouteImport.update({
  id: '/hero-slides',
  path: '/hero-slides',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDonationsRoute = AdminDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactSettingsRoute = AdminContactSettingsRouteImport.update({
  id: '/contact-settings',
  path: '/contact-settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAboutSettingsRoute = AdminAboutSettingsRouteImport.update({
  id: '/about-settings',
  path: '/about-settings',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/news': typeof NewsRoute
  '/projects': typeof ProjectsRoute
  '/volunteer': typeof VolunteerRoute
  '/admin/about-settings': typeof AdminAboutSettingsRoute
  '/admin/contact-settings': typeof AdminContactSettingsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/hero-slides': typeof AdminHeroSlidesRoute
  '/admin/home-settings': typeof AdminHomeSettingsRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/programs/': typeof ProgramsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/news': typeof NewsRoute
  '/projects': typeof ProjectsRoute
  '/volunteer': typeof VolunteerRoute
  '/admin/about-settings': typeof AdminAboutSettingsRoute
  '/admin/contact-settings': typeof AdminContactSettingsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/hero-slides': typeof AdminHeroSlidesRoute
  '/admin/home-settings': typeof AdminHomeSettingsRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/programs': typeof ProgramsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/news': typeof NewsRoute
  '/projects': typeof ProjectsRoute
  '/volunteer': typeof VolunteerRoute
  '/admin/about-settings': typeof AdminAboutSettingsRoute
  '/admin/contact-settings': typeof AdminContactSettingsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/hero-slides': typeof AdminHeroSlidesRoute
  '/admin/home-settings': typeof AdminHomeSettingsRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/programs/': typeof ProgramsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/donate'
    | '/events'
    | '/news'
    | '/projects'
    | '/volunteer'
    | '/admin/about-settings'
    | '/admin/contact-settings'
    | '/admin/dashboard'
    | '/admin/donations'
    | '/admin/events'
    | '/admin/hero-slides'
    | '/admin/home-settings'
    | '/admin/news'
    | '/admin/programs'
    | '/admin/projects'
    | '/admin/submissions'
    | '/programs/$slug'
    | '/admin/'
    | '/programs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/donate'
    | '/events'
    | '/news'
    | '/projects'
    | '/volunteer'
    | '/admin/about-settings'
    | '/admin/contact-settings'
    | '/admin/dashboard'
    | '/admin/donations'
    | '/admin/events'
    | '/admin/hero-slides'
    | '/admin/home-settings'
    | '/admin/news'
    | '/admin/programs'
    | '/admin/projects'
    | '/admin/submissions'
    | '/programs/$slug'
    | '/admin'
    | '/programs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/donate'
    | '/events'
    | '/news'
    | '/projects'
    | '/volunteer'
    | '/admin/about-settings'
    | '/admin/contact-settings'
    | '/admin/dashboard'
    | '/admin/donations'
    | '/admin/events'
    | '/admin/hero-slides'
    | '/admin/home-settings'
    | '/admin/news'
    | '/admin/programs'
    | '/admin/projects'
    | '/admin/submissions'
    | '/programs/$slug'
    | '/admin/'
    | '/programs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  EventsRoute: typeof EventsRoute
  NewsRoute: typeof NewsRoute
  ProjectsRoute: typeof ProjectsRoute
  VolunteerRoute: typeof VolunteerRoute
  ProgramsSlugRoute: typeof ProgramsSlugRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/': {
      id: '/programs/'
      path: '/programs'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/programs/$slug': {
      id: '/programs/$slug'
      path: '/programs/$slug'
      fullPath: '/programs/$slug'
      preLoaderRoute: typeof ProgramsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/programs': {
      id: '/admin/programs'
      path: '/programs'
      fullPath: '/admin/programs'
      preLoaderRoute: typeof AdminProgramsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/home-settings': {
      id: '/admin/home-settings'
      path: '/home-settings'
      fullPath: '/admin/home-settings'
      preLoaderRoute: typeof AdminHomeSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hero-slides': {
      id: '/admin/hero-slides'
      path: '/hero-slides'
      fullPath: '/admin/hero-slides'
      preLoaderRoute: typeof AdminHeroSlidesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/donations': {
      id: '/admin/donations'
      path: '/donations'
      fullPath: '/admin/donations'
      preLoaderRoute: typeof AdminDonationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contact-settings': {
      id: '/admin/contact-settings'
      path: '/contact-settings'
      fullPath: '/admin/contact-settings'
      preLoaderRoute: typeof AdminContactSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/about-settings': {
      id: '/admin/about-settings'
      path: '/about-settings'
      fullPath: '/admin/about-settings'
      preLoaderRoute: typeof AdminAboutSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAboutSettingsRoute: typeof AdminAboutSettingsRoute
  AdminContactSettingsRoute: typeof AdminContactSettingsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDonationsRoute: typeof AdminDonationsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminHeroSlidesRoute: typeof AdminHeroSlidesRoute
  AdminHomeSettingsRoute: typeof AdminHomeSettingsRoute
  AdminNewsRoute: typeof AdminNewsRoute
  AdminProgramsRoute: typeof AdminProgramsRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAboutSettingsRoute: AdminAboutSettingsRoute,
  AdminContactSettingsRoute: AdminContactSettingsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDonationsRoute: AdminDonationsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminHeroSlidesRoute: AdminHeroSlidesRoute,
  AdminHomeSettingsRoute: AdminHomeSettingsRoute,
  AdminNewsRoute: AdminNewsRoute,
  AdminProgramsRoute: AdminProgramsRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  EventsRoute: EventsRoute,
  NewsRoute: NewsRoute,
  ProjectsRoute: ProjectsRoute,
  VolunteerRoute: VolunteerRoute,
  ProgramsSlugRoute: ProgramsSlugRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
